name: Build docker container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker tags
        id: docker-tags
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/nedap/synapse
          flavor: |
            latest=false
            prefix=,onlatest=true
            suffix=,onlatest=true
          # Tag each Git commit, branch and tag
          # Tag `latest` if this commit is on the default branch
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Build Runtime
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          no-cache: true
          tags: ${{ steps.docker-tags.outputs.tags }}
          build-args: |
            GITHUB_PACKAGES_TOKEN=${{ github.token }}
            GITHUB_PACKAGES_USER=${{ github.actor }}
